name: Python Linting and Formatting

on:
  push:
    branches:
      - '**' 
  pull_request:
    branches:
      - '**' 

jobs:
  lint_and_format:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      - name: Python Linter
        uses: sunnysid3up/python-linter@master
        with:
          source: "src"
          mypy-options: "--ignore-missing-imports --show-error-codes"
          pylint-options: "--rcfile=setup.cfg"
          isort-options: "-w 100"
          django: true

          